# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-22 07:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2017, 12, 22, 7, 7, 17, 800876, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
